GET http://localhost:8000/users

###
POST http://localhost:8000/signup
Content-Type: application/json

{
  "username": "cr1c5",
  "password": "12345"
}

###
POST http://localhost:8000/signin
Content-Type: application/json

{
  "username": "cr1c5",
  "password": "12"
}


