# GET all notes
GET http://localhost:10000/cr1c4/notes

### POST add note
POST http://localhost:10000/cr1c4/notes
Content-Type: application/json

{
  "title": "Note title cr1c4",
  "description": "Note description cr1c4"
}

### PUT UPDATE NOTE
PUT http://localhost:10000/notes/
Content-Type: application/json

{
  "title": "Note edited",
  "description": "Description changed"
}

### DELETE delete note
DELETE http://localhost:10000/cr1c4/notes/615fc9e59fad9b5f337a5447