# GET all notes
GET http://localhost:10000/cr1c4/notes
x-access-token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNWZhZGNmYWI2NDY1YzI0ODkzMjY5MiJ9.7KZ4EQHs97zwEHNdrmYR7sLhAvPUdIN_e14LQ9g7Ju20zei00CTzvg-shiGvNkx-8XUriTqlDQqQHp5N_ObhTQ

### POST add note
POST http://localhost:10000/cr1c4/notes
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNWZhZGNmYWI2NDY1YzI0ODkzMjY5MiJ9.7KZ4EQHs97zwEHNdrmYR7sLhAvPUdIN_e14LQ9g7Ju20zei00CTzvg-shiGvNkx-8XUriTqlDQqQHp5N_ObhTQ

{
  "title": "Note title cr1c4",
  "description": "Note description cr1c4"
}

### PUT UPDATE NOTE
PUT http://localhost:10000/cr1c4/notes/616074794ea8fdb72834f39b
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNWZhZGNmYWI2NDY1YzI0ODkzMjY5MiJ9.7KZ4EQHs97zwEHNdrmYR7sLhAvPUdIN_e14LQ9g7Ju20zei00CTzvg-shiGvNkx-8XUriTqlDQqQHp5N_ObhTQ

{
  "title": "Note edited",
  "description": "Description changed"
}

### DELETE delete note
DELETE http://localhost:10000/cr1c4/notes/615fcb64900d49e1b869ab64
x-access-token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNWZhZGNmYWI2NDY1YzI0ODkzMjY5MiJ9.7KZ4EQHs97zwEHNdrmYR7sLhAvPUdIN_e14LQ9g7Ju20zei00CTzvg-shiGvNkx-8XUriTqlDQqQHp5N_ObhTQ