GET http://localhost:10000/615fadcfab6465c248932692

###
GET http://localhost:10000/users 

###
POST http://localhost:10000/signup
Content-Type: application/json

{
  "username": "cr1c5",
  "password": "12345"
}

###
DELETE http://localhost:10000/615fad18078a5e9e1a0f1de5


